[project]
name = "mahjong-calculator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pytest>=9.0.2",
    "sortedcontainers>=2.4.0",
    "sortedcontainers-stubs>=2.4.3",
]
